/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Validations;
import java.sql.Connection;
import java.sql.*;
import view.ItemPanel;
/**
 *
 * @author ASUS
 */
public class ItemDeleteConfirmationMessage extends javax.swing.JFrame {

    private String itemId;
    private ItemPanel parent;
    private Connection con;
    
    /**
     * Creates new form deleteconfirmationMessage
     */
    public ItemDeleteConfirmationMessage(ItemPanel parent, String itemId) {
        initComponents();
        this.parent = parent;
        this.itemId = itemId;
        this.con = parent.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnyesno = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbYes = new javax.swing.JButton();
        jbNo = new javax.swing.JButton();
        menu1 = new GradienTandIcons.Gradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Are you sure you want to delete this Item  ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jbYes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbYes.setText("YES");
        jbYes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102), 2));
        btnyesno.add(jbYes);
        jbYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbYesActionPerformed(evt);
            }
        });
        jPanel1.add(jbYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 113, 69, -1));

        jbNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbNo.setText("NO");
        jbNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 2));
        btnyesno.add(jbNo);
        jbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNoActionPerformed(evt);
            }
        });
        jPanel1.add(jbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 113, 69, -1));

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 440, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbYesActionPerformed

       try {
        int Item_id = Integer.parseInt(itemId);
        Statement stmt = con.createStatement();
        String query = "DELETE FROM Items WHERE Item_id = " + Item_id;

        int result = stmt.executeUpdate(query);

        if (result == 1) {
            DeletionSuccessMessage idsm = new DeletionSuccessMessage();
            idsm.setVisible(true);
            parent.Item_Load();
            
        } else {
            ErrorDeletingMesage edim = new ErrorDeletingMesage();
            edim.setVisible(true);
        }

    } catch (NumberFormatException e) {
        IDValidation iiv = new IDValidation();
        iiv.setVisible(true);
    } catch (SQLException ex) {
        DBErrorMessage dbe = new DBErrorMessage();
        dbe.setVisible(true);
    } finally {
        this.dispose();
    } 
    
    }//GEN-LAST:event_jbYesActionPerformed

    private void jbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemDeleteConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemDeleteConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemDeleteConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemDeleteConfirmationMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnyesno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbNo;
    private javax.swing.JButton jbYes;
    private GradienTandIcons.Gradient menu1;
    // End of variables declaration//GEN-END:variables
}
